config/routes.rb
Surfeitalpha::Application.routes.draw do
  root to: "pages#current"

  get '/remove_authorizations' => 'authorizations#destroy', :as => :remove_authorizations
  get '/current' => 'pages#current', :as => :user_current

  match 'session/instagram', :to => 'authorizations#instagram',  :as => :authorize_instagram
  match 'session/facebook', :to => 'authorizations#facebook',  :as => :authorize_facebook
  match 'auth/twitter/callback', :to => 'authorizations#twitter', :as => :authorize_twitter # auth/twitter/callback needs to change to session/twitter PLEASE!

  resource  :session  
  resources  :authorizations  

  resources :users 
  resources :stashes

  get '/sessions/destroy' => 'sessions#destroy', :as => :logout

end



# get '/login' => 'sessions#login', :as => :login
# post '/sessions/create' => 'sessions#create_surfeit'
# match 'auth/twitter/callback', :to => 'sessions#create_twitter', :as => :twitter_auth
# match 'auth/facebook/callback', :to => 'sessions#create_facebook', :as => :facebook_auth
# match 'auth/failure', :to => 'sessions#failure'
# get '/sessions/logout' => 'sessions#destroy', :as => :logout

app/models/user.rb
class User < ActiveRecord::Base

	include Gravtastic
  gravtastic

  attr_accessible :email, :name, :password, :password_confirmation, :username, :email_opt_in

  has_many :access_tokens

  has_secure_password

  validates_presence_of :name, :email
  validates_uniqueness_of :email, :username

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..15},
                       :on => :create
  validates :password, :confirmation => true,
                       :length => {:within => 6..15},
                       :allow_blank => true,
                       :on => :update


  before_validation do
  		self.username = self.username.downcase
  		self.email = self.email.downcase
	end

  def self.from_omniauth(auth)
	where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
	end

	def access_token(service)
		token = AccessToken.find_by_user_id_and_service(id, service)
		token ? token.access_token : false
	end

	def access_token_secret(service)
		token = AccessToken.find_by_user_id_and_service(id, service)
		token ? token.access_token_secret : false
	end

	def self.create_from_omniauth(auth)

		create! do |user|
			user.provider = auth["provider"]
			user.uid = auth["uid"]
			user.name = auth["info"]["name"]
			user.username = ["authinfo"]["username"]
			user.password = auth["uid"]
			user.email = auth["info"]["email"]			
		end
		
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :ensure_correct_user_id, :except => [:new, :create]
  skip_before_filter :authenticate!, :only => ['new', 'create']

  def ensure_correct_user_id
    if session[:user_id] != params[:id].to_i
      flash[:notice] = "You are not authorized to see/edit/delete any other User's user information."
      redirect_to user_url(session[:user_id])
      return
    end
  end


  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(params[:user])
    (@user.save) ? (session[:user_id] = @user.id ; redirect_to(authorizations_path)) : (redirect_to new_user_path, :notice => "Not enough rights to go here man")

  end


  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user]) ? (redirect_to @user, notice: 'User was successfully updated.') :  (render action: "edit") 
  end

 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
  
  end
end

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  	<div class="shebang">
    <span class="nameInput">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    </span>
    </br>
     <span class="userInput">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username %>
    </span>
    </br>
    <span class="emailInput">
    <%= f.label :email, "Email" %>
    <%= f.email_field :email %>
    </span><br>
    <span class="pwdInput">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
    </span></br>
    <span class="pwdConfirm">
    <%= f.label :password_confirmation, "Confirm" %>
    <%= f.password_field :password_confirmation %>
    </span></br>

    <div class="actions">
    	<%= f.submit "SUBMIT", :class => "aboard" %>
    </div>
    
    </div>
	
<% end %> 

    

app/views/users/_form_edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>
      <% @user.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
      
    </div>
  <% end %>

    <span class="nameInput">
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
    </span> <br><br>
     <span class="userInput">
    <%= f.label :username, "Username:" %>
    <%= f.text_field :username %>
    </span> <br><br>
    <span class="emailInput">
    <%= f.label :email, "Email:" %>
    <%= f.email_field :email %>
    </span><br><br>
    <span class="pwdInput">
    <%= f.label :password, "Password:" %>
    <%= f.password_field :password %>
    </span><br>
    <br>
    <span class="pwdConfirm">
    <%= f.label :password_confirmation, "Confirm:" %>
    <%= f.password_field :password_confirmation %>
    </span><br>

    <div class="actions">
    	<%= f.submit "Update Account" %>
    </div>
	
<% end %> 

app/views/users/edit.html.erb
 <head>
<title>Surfeit Beta!</title>
  
  <%= stylesheet_link_tag "editUser", :media => "all" %>
  <%= stylesheet_link_tag "theGrid", :media => "all" %>
</head>

  <body>
  <div class="container">
	<div class="twelvecol last">
		<div class="nombre">
			<p class="surfeitTitle">SURFEIT<span class="betaTag" style="font-size: 66px;">beta</span></p>
		</div>
				
		<div class="motto">
			<p class="mottoLabel">Edit Account</p>
		</div>
	</div>
	
	<div class="twelvecol last" style="height: 477px;">
		<div class="fixit" style="height: 477px;">
			<div class="formHolder">
			<%= render 'form_edit' %>
			</div>
			<div class="cubicHolder">
			<div class="logoHolder">
				<%= image_tag "SurfeitLogo.svg", :class => "logo" %>
			</div>
			
			<div class="sliderHex">
				<div class="slideCube">
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			<div class="signUpHex">
				<div class="signUpCube">
					<div class="engraving">
					<%= link_to "BACK", users_path, :class => "backstep" %>
					</div>
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			</div>
		</div>
	
	
			<div class=navHolder>
				<nav>
					<%= link_to 'Current', user_current_path %> |
					<%= link_to 'Networks', authorizations_path %> |
					<%= link_to "Account", users_path %> | 
					<%= link_to "Sign Out", logout_path %>
				</nav>
			</div>
		</div>
	</div> 	
</body>

app/views/users/index.html.erb
<h1> User Index </h1>

<table>
	<tr>
	  <th>Name</th>
	  <th>Email</th>
	  <th>Username</th>
	  <th></th>
	  <th></th>
	  <th></th>
	</tr>
	
<% current_user do |user| %>
	<tr>
	  <td><%= user.name %></td>
	  <td><%= user.email %></td>
	  <td><%= user.username %></td>
	  <td><%= link_to 'show',  %></td>
	  <td><%= link_to 'edit'  %></td>

	 	
	 </tr>
	<% end %>
</table>

<br />

 

app/views/users/new.html.erb
<head>
	<title>Surfeit Alpha!</title>
	
		 <%= stylesheet_link_tag "newUser", :media => "all" %>
		 <%= stylesheet_link_tag "theGrid", :media => "all" %>
		 <%= stylesheet_link_tag "slide", :media => "all" %>
		 
		 <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
		 <%= javascript_include_tag "modernizr" %>

</head>

<body>

<div class="container">
	<div class="twelvecol last">
		<div class="nombre">
			<p class="surfeitTitle">SURFEIT<span class="betaTag" style="font-size: 66px;">beta</span></p>
		</div>
				
		<div class="motto">
			<p class="mottoLabel">CREATE ACCOUNT</p>
		</div>
	</div>
	
	<div class="twelvecol last" style="height: 477px;">
		<div class="fixit" style="height: 477px;">
			<div class="formHolder">
			<%= render 'form' %>
			</div>
			<div class="cubicHolder">
			<div class="logoHolder">
				<%= image_tag "SurfeitLogo.svg", :class => "logo" %>
			</div>
			
			<div class="sliderHex">
				<div class="slideCube">
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			<div class="signUpHex">
				<div class="signUpCube">
				<div class="engraving">
					<%= link_to "BACK", users_path, :class => "backstep" %>
				</div>
					
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			</div>
		</div>
	</div>
</div> 
</body>

<!--
<head>
<title>Surfeit Alpha</title>
  
  <%= stylesheet_link_tag "newUser", :media => "all" %>
  <%= stylesheet_link_tag "theGrid", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
</head>
 
<body>

<div class="mobileTrigger">
	</div>
	<div class="container nonMobile">
		<div class="row colorBlack">
			<div class="fourcol colorMint">
				<div class="signUpHolder colorSky">
				
				</div>
			</div>
			
			<div class="fourcol z2">
				<div class="logoBox colorMint">
					<h1 class="surfeitLogoTitle">Surfeit</h1>
					<div class="logoHolder">
					<%= image_tag "SurfeitLogo.svg", :class => "surfeitLandingLogo" %>
					</div>
				</div>
			</div>
			
			<div class="fourcol last colorMint">
			<div class="loginFormBox colorSunnyD">
				
			</div>
			</div>
		
		</div>
		
		<div class="row colorBlack z1 secondRow">
			<div class="fourcol cake">
				<div class="colorSky frosting">
					<div class="thingOne colorBlack">
					
					</div>
					
					<div class="thingTwo colorBlack">
					
					</div>
				</div>
			</div>
			
			<div class="fourcol cake center">
				<div class="creamWrap colorMint">
					<div class="thingOne colorBlack">
					
					</div>
					
					<div class="thingTwo colorBlack">
					
					</div>
				
				</div>
			</div>
			
			<div class="fourcol cake last">
			<div class="colorSunnyD frosting">
					<div class="thingOne colorBlack">
					
					</div>
					
					<div class="thingTwo colorBlack">
					
					</div>
				</div>
			</div>
			
		</div>
		
		<div class="row colorBlack z2 thirdRow"> 
			<div class="threecol">
				<div class="blueBeamLayerOne colorSky">
					<div class="hocus colorBlack">
					
					</div>
					<div class="pocus colorBlack">
					
					</div>
				</div>
				
				<div class="blueBeamLayerTwo">
					<div class="blueBeamLensOne">
					</div>
					
					<div class="blueBeamLensTwo colorBlack">
					</div>
				</div>
				
				<div class="sapphireSocket">
					<div class="kruxOne sapphire">
				
					</div>
				</div>
				
				<div class="blueBeamLensThree colorSky">
					<div class="echo colorBlack">
					
					</div>
					<div class="gecko colorBrick">
					<div class="mortar1 colorBlack">
					</div>
					</div>
				</div>
			</div>
			
			
			<div class="sixcol sliderHolder z3">
				<div class="fixture colorMint">
					<div class="fixieOne colorBlack">
					</div>
					<div class="fixieTwo colorBlack">
					</div>
				</div>
				
				<div class="television colorMint">
					<div class="teleScreen">
						<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
					<%= render 'form' %>
					</div>
				</div>
				
				<div class="teleBase">
				</div>
			</div>
			
			<div class="threecol last">
				<div class="orangeBeamLayerOne colorSunnyD">
					<div class="hocusTwo colorBlack">
					
					</div>
					<div class="pocusTwo colorBlack">
					
					</div>
				</div>
				
				<div class="orangeBeamLayerTwo">
					<div class="orangeBeamLensOne">
					</div>
					
					<div class="orangeBeamLensTwo colorBlack">
					</div>
					
					
				</div>
				<div class="amberSocket">
					<div class="kruxOne amber">
				
					</div>
				</div>
				
				<div class="orangeBeamLensThree colorSunnyD">
					<div class="echo2 colorBrick">
					<div class="mortar2 colorBlack">
					</div>
					</div>
					<div class="gecko2 colorBlack">
					
					</div>
				</div>
			
			</div>
		</div>
		
		<div class="row colorBrick z3 footerRow">
			<div class="twelvecol footercol last">
			</div>
		</div>
	</div>			   

	<div class="container mobile">
		<div class="row">
			<div class="twelvecol last">
			<div class="logoBox colorMint">
					<h1 class="surfeitLogoTitle">Surfeit</h1>
					<div class="logoHolder">
					<%= image_tag "SurfeitLogo.svg", :class => "surfeitLandingLogo" %>
					</div>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="twelvecol secondMobileRow last">
			<div class="creamWrap colorMint">
					<div class="thingOne colorBlack">
					
					</div>
					
					<div class="thingTwo colorBlack">
					
					</div>
					<div class="signInMobileHolder colorBlack">
					<%= render 'form' %>
					</div>
				</div>
			</div>
		</div>
		
		<div class="row">
			<div class="twelvecol last thirdMobileRow">
			
			<div class="signUpBox colorSunnyD">
				<div class="cheech colorBlack">
				
				</div>
				
				<div class="chong colorBlack">
				
				</div>
				
				
			</div>
			
			</div>
		</div>
	</div>

	<%= javascript_include_tag "jquery-1.7.1.min" %>
	<script type="text/javascript">
		// global variables
		var compareColor; //previous color used for comparison
		var trigger; //the element used to compare changes
		// for performance, I store the detector element into a variable to avoid
		// running a DOM query every time we need to test the change conditions
		var nonMobileHolder
		var mobileHolder
		var wereCoolHolder
		jQuery(document).ready(function(){
		
		    //set the initial values
		    trigger = $('.mobileTrigger');
		    compareColor = trigger.css('color');
		    nonMobileHolder = $('.nonMobile');
		    mobileHolder = $('.mobile');
		    wereCoolHolder = $('.wereCool');
		    
		    $('.mobile').remove();
		    if(trigger.css('color')== 'rgb(255, 0, 0)'){
		            $('.nonMobile').remove();
		            $('body').append(mobileHolder);
		            wereCoolHolder.remove();
		    };
		    
		    $(window).resize(function(){
		        //compare everytime the window resize event fires
		        if(trigger.css('color')== 'rgb(255, 0, 0)'){
		            $('.nonMobile').remove();
		            if($('body').children('.mobile').size() == 0){
		            $('body').append(mobileHolder);
		            wereCoolHolder.remove();
		            }
		        }
		        else if($('body').children('.nonMobile').size() > 0){
				        return
				}
			    else{
			    	$('.mobile').remove();
				    $('body').append(nonMobileHolder);				    
			    }
		        
		
		    });
		
		});
		</script>
	<!--
<header>
    	<div class="headerContent">
	      <h1 class="surfeitTextLogo">Surfeit</h1>
	      <%= image_tag 'SurfeitLogo.svg', :class => 'surfeitLogo' %>
	      <%= link_to "Already have an account?", new_session_path , :class => 'alreadyMember' %>
    	</div>
    </header>
    
    
    <div class="container">
    	<%= render 'form' %>
    </div>
    <br>
-->

</body>

app/views/users/show.html.erb
<!--
  <div class="navBar">
    <header>
      <nav>
            <%= "Surfeit" %>
            <%= '[SurfeitLogo]' %>
            <%= link_to 'Current', user_current_path %> |
            <%= link_to 'Networks', authorizations_path %> |
            <%= link_to "Account", users_path %> | 
            <%= current_user.name.capitalize %> 
            <%= link_to "Sign Out", logout_path %>
      </nav>
    </header>

<h1> My Account </h1>


<%= link_to 'Edit My Info & Change Password', edit_user_path %>
<p> Name: <%= current_user.name.capitalize %> </p>
<p>Email: <%= current_user.email %> </p>
<p>Username: <%= current_user.username%></p>


<%= image_tag @user.gravatar_url %>
-->

 <head>
<title>Surfeit Beta!</title>
  
  <%= stylesheet_link_tag "showUser", :media => "all" %>
  <%= stylesheet_link_tag "theGrid", :media => "all" %>
</head>

  <body>
  <div class="container">
	<div class="twelvecol last">
		<div class="nombre">
			<p class="surfeitTitle">SURFEIT<span class="betaTag" style="font-size: 66px;">beta</span></p>
		</div>
				
		<div class="motto">
			<p class="mottoLabel">My Account</p>
		</div>
	</div>
	
	<div class="twelvecol last" style="height: 477px;">
		<div class="fixit" style="height: 477px;">
			<div class="formHolder">
			
			<p style="font-weight: 900;">Name</p>
			<p><%= current_user.name.capitalize %> </p>
			<p style="font-weight: 900;">Email</p> 
			<p><%= current_user.email %> </p>
			<p style="font-weight: 900;">Username</p> 
			<p><%= current_user.username%></p>
			</div>
			<div class="cubicHolder">
			<div class="logoHolder">
				<%= image_tag "SurfeitLogo.svg", :class => "logo" %>
			</div>
			
			<div class="sliderHex">
				<div class="slideCube">
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			<div class="signUpHex">
				<div class="signUpCube">
				<div class="engraving">
				<%= link_to 'EDIT', edit_user_path, :class => "editor" %>
				</div>
					
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			</div>
		</div>
	
	
			<div class=navHolder>
				<nav>
					<%= link_to 'Current', user_current_path %> |
					<%= link_to 'Networks', authorizations_path %> |
					<%= link_to "Account", users_path %> | 
					<%= link_to "Sign Out", logout_path %>
				</nav>
			</div>
		</div>
	</div> 	
</body>