config/routes.rb
Surfeitalpha::Application.routes.draw do
  root to: "pages#current"

  get '/remove_authorizations' => 'authorizations#destroy', :as => :remove_authorizations
  get '/current' => 'pages#current', :as => :user_current

  match 'session/instagram', :to => 'authorizations#instagram',  :as => :authorize_instagram
  match 'session/facebook', :to => 'authorizations#facebook',  :as => :authorize_facebook
  match 'auth/twitter/callback', :to => 'authorizations#twitter', :as => :authorize_twitter # auth/twitter/callback needs to change to session/twitter PLEASE!

  resource  :session  
  resources  :authorizations  

  resources :users 
  resources :stashes

  get '/sessions/destroy' => 'sessions#destroy', :as => :logout

end



# get '/login' => 'sessions#login', :as => :login
# post '/sessions/create' => 'sessions#create_surfeit'
# match 'auth/twitter/callback', :to => 'sessions#create_twitter', :as => :twitter_auth
# match 'auth/facebook/callback', :to => 'sessions#create_facebook', :as => :facebook_auth
# match 'auth/failure', :to => 'sessions#failure'
# get '/sessions/logout' => 'sessions#destroy', :as => :logout

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  
  def index	  
 	end

 	def destroy
 		current_user.access_tokens.where(service: params[:service]).destroy_all
 		redirect_to authorizations_path
 	end

 	def instagram
	  response = Instagram.get_access_token(params[:code], redirect_uri: authorize_instagram_url)
	  
	  AccessToken.create(
	  	access_token: response.access_token, 
	  	user_id: current_user.id, 
	  	service: 'instagram'
	  )
	  
	  redirect_to authorizations_path
 	end

 	def facebook
		response = Koala::Facebook::OAuth.new('333831113381266', '43e26a8d150ba3db9a0308031fdbfd86', authorize_facebook_url)
		
		 AccessToken.create(
	  	access_token: response.get_access_token(params[:code]), 
	  	user_id: current_user.id, 
	  	service: 'facebook'
	  )

	  redirect_to authorizations_path, :notice => 'User Was successfully authorized!!!'
  end

  def twitter
  
  	response = env['omniauth.auth']
  	
  	
	  AccessToken.create(
	  	access_token: response.credentials.token,
	  	access_token_secret: response.credentials.secret, 
	  	user_id: current_user.id, 
	  	service: 'twitter'
	  )
	  
	  redirect_to authorizations_path
  end



end

app/views/authorizations/index.html.erb
<!--
<h1>Authorized websites to pull data from:</h1>

<ul>
	<% unless current_user.access_token('instagram').present? %>
  	<li><%= link_to "Authorize Instagram", Instagram.authorize_url(redirect_uri: authorize_instagram_url) %></li>
  <% end %>

  <% unless current_user.access_token('facebook').present? %>
  	<li><%= link_to 'Authorize this Facebook app', facebook_auth_url , :class=>"button" %></li>
  <% end %>

  <% unless current_user.access_token('twitter').present? && current_user.access_token_secret('twitter').present? %>
    <li><%= link_to 'Authorize this Twitter app', 'auth/twitter', :class=>"button" %></li>
  <% end %>
</ul>


<ul>
	<% if current_user.access_token('instagram').present? %>
  	<li><%= link_to "Deauthorize Instagram",'#' %></li>


  <% end %>

  <% if current_user.access_token('facebook').present? %>
  	<li><%= link_to 'Deauthorize Facebook', '#'%></li>
  <% end %>

  <% if current_user.access_token('twitter').present? && current_user.access_token_secret('twitter').present? %>
    <li><%= link_to "Deauthorize Twitter", '#' %></li>
  <% end %>
</ul>
-->
<head>
	<title>Surfeit Beta!</title>
	
		 <%= stylesheet_link_tag "feedManagement", :media => "all" %>
		 <%= stylesheet_link_tag "theGrid", :media => "all" %>
		 <%= stylesheet_link_tag "slide", :media => "all" %>
		 
		 <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
		 <%= javascript_include_tag "modernizr" %>

</head>

<body>

<div class="container">
	<div class="twelvecol last">
		<div class="nombre">
			<p class="surfeitTitle">SURFEIT<span class="betaTag" style="font-size: 66px;">beta</span></p>
		</div>
				
		<div class="motto">
			<p class="mottoLabel">Authorize Networks</p>
		</div>
	</div>
	
	<div class="twelvecol last" style="height: 477px;">
		<div class="fixit" style="height: 477px;">
			<div class="globeHolder">
			
			</div>
			<div class="cubicHolder">
			<div class="sliderHex">
				<div class="slideCube">
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
				</div>
			</div>
			<div class="signUpHex">
				<div class="signUpCube">	
					<div class="engraving">
					<% unless current_user.access_token('facebook').present? %>
						<%= link_to 'F', facebook_auth_url , :class => "unauthorizedFacebook" %>
					<% end %>
					
					<% if current_user.access_token('facebook').present? %>
						<%= link_to 'F', remove_authorizations_path(:service => 'facebook'), :class => "authorizedFacebook" %>
					<% end %>
					</div>
					<% unless current_user.access_token('facebook').present? %>
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
					<% end %>
					
					<% if current_user.access_token('facebook').present? %>
					<div class="top activate"></div>
					<div class="left activate"></div>
					<div class="right activate"></div> 	
					<% end %>
				</div>
			</div>
			
			<div class="signUpHex2">
				<div class="signUpCube">
					<div class="engraving">
					
					<% unless current_user.access_token('instagram').present? %>
						<%= link_to "D", Instagram.authorize_url(redirect_uri: authorize_instagram_url), :class => "unauthorizedInsta" %>
  					<% end %>
  					
  					<% if current_user.access_token('instagram').present? %>
						<%= link_to "D", remove_authorizations_path(:service => 'instagram'), :class => "authorizedInsta" %>
  					<% end %>
  					
					</div>
					<% unless current_user.access_token('instagram').present? %>
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 	
					<% end %>
					
					<% if current_user.access_token('instagram').present? %>
					<div class="top activate2"></div>
					<div class="left activate2"></div>
					<div class="right activate2"></div> 	
					<% end %>	
				</div>
			</div>
			
			<div class="signUpHex3">
				<div class="signUpCube">
					<div class="engraving">
					<% unless current_user.access_token('twitter').present? && current_user.access_token_secret('twitter').present? %>
						<%= link_to "L", 'auth/twitter', :class => "unauthorizedTwitter" %>
					<%end%>
					
					<% if current_user.access_token('twitter').present? && current_user.access_token_secret('twitter').present? %>
						<%= link_to "L", remove_authorizations_path(:service => 'twitter') , :class => "authorizedTwitter" %>
					<%end%>
					</div>
					<% unless current_user.access_token('twitter').present? && current_user.access_token_secret('twitter').present? %>
					<div class="side top"></div>
					<div class="side left"></div>
					<div class="side right"></div> 
					<%end%>
					
					<% if current_user.access_token('twitter').present? && current_user.access_token_secret('twitter').present? %>
					<div class="top activate3"></div>
					<div class="left activate3"></div>
					<div class="right activate3"></div> 
					<%end%>
						
				</div>
			</div>
			</div>
			
		</div>
		<div class=navHolder>
				<nav>
					<%= link_to 'Current', user_current_path %> |
					<%= link_to 'Networks', authorizations_path %> |
					<%= link_to "Account", users_path %> | 
					<%= link_to "Sign Out", logout_path %>
				</nav>
			</div>
	</div>
</div> 
</body>